language: r

warnings_are_errors: true

cache: packages

sudo: required

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      before_install:
        - mkdir -p  ~/.R
        - echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true

env:
 global:
   - CRAN: http://cran.rstudio.com

addons:
  apt:
    packages:
      - libhunspell-dev
      - libpoppler-cpp-dev

r_github_packages:
  - r-lib/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
